"""Pydantic models describing asset ingest payloads."""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class VcfIngestRequest(BaseModel):
	"""Payload emitted by the ingest pipeline when summarising a VCF."""

	source: str = Field(description="Path or URI of the original VCF dataset")
	records: int = Field(ge=0, description="Number of variant records in the VCF")
	samples: list[str] = Field(default_factory=list, description="Sample identifiers present")
	created_at: datetime = Field(description="Timestamp generated by the pipeline")
	gfa_stats: dict[str, Any] | None = Field(
		default=None, description="Optional summaries for the paired GFA asset"
	)


class VcfIngestRecord(BaseModel):
	"""Representation of a persisted VCF ingest summary."""

	model_config = ConfigDict(from_attributes=True)

	id: int
	source: str
	records: int
	samples: list[str]
	gfa_stats: dict[str, Any] | None = None
	created_at: datetime
	ingested_at: datetime
